<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="PC" ignored="0" name="Test" tests="2" failures="2" timestamp="26 May 2020 03:18:09 GMT" time="9.197" errors="0">
  <testcase name="feature" time="7.541" classname="cucumberoptions.TestRunner">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at stepDefinations.restAssuredStepdefPOst.a_list_of_book_available(restAssuredStepdefPOst.java:156)
at âœ½.A list of book available(file:///C:/selenium/mavenproj/src/test/java/features/RestAssuredPostOperation.feature:20)
]]>
    </failure>
  </testcase> <!-- feature -->
  <testcase name="feature" time="7.589" classname="cucumberoptions.TestRunner">
    <failure type="org.testng.TestNGException" message="java.util.concurrent.ExecutionException: java.lang.NullPointerException">
      <![CDATA[org.testng.TestNGException: java.util.concurrent.ExecutionException: java.lang.NullPointerException
Caused by: java.util.concurrent.ExecutionException: java.lang.NullPointerException
at java.util.concurrent.FutureTask.report(Unknown Source)
at java.util.concurrent.FutureTask.get(Unknown Source)
... 18 more
Caused by: java.lang.NullPointerException
at resources.TestBase.TakesSnapshot(TestBase.java:66)
at com.listeners.TestNGListeners.onTestFailure(TestNGListeners.java:31)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 26 stack frames]]>
    </failure>
  </testcase> <!-- feature -->
</testsuite> <!-- Test -->
